"""Static pantry vocabulary (LLD §8.4): keyword -> category, plus setup-screen suggestions.

Keys are stored normalised (see services.normalize.normalize_name) so lookups use the same form as stored names.
"""

from larder.services.normalize import normalize_name

CATEGORY_ORDER: list[str] = [
    "vegetables",
    "fruits",
    "dairy",
    "proteins",
    "pulses",
    "grains",
    "flours",
    "spices",
    "condiments",
    "oils",
    "frozen",
    "snacks",
    "beverages",
    "other",
]

CATEGORY_LABELS: dict[str, str] = {
    "vegetables": "Vegetables",
    "fruits": "Fruits",
    "dairy": "Dairy",
    "proteins": "Proteins, nuts & seeds",
    "pulses": "Pulses & legumes",
    "grains": "Grains & cereals",
    "flours": "Flours & baking",
    "spices": "Spices & herbs",
    "condiments": "Condiments & sauces",
    "oils": "Oils & fats",
    "frozen": "Frozen",
    "snacks": "Snacks",
    "beverages": "Beverages",
    "other": "Other",
}

_RAW: dict[str, list[str]] = {
    "spices": [
        "salt",
        "black salt",
        "rock salt",
        "cumin",
        "cumin seeds",
        "jeera",
        "coriander seeds",
        "coriander powder",
        "dhania powder",
        "turmeric",
        "haldi",
        "red chilli powder",
        "chilli powder",
        "kashmiri chilli powder",
        "garam masala",
        "mustard seeds",
        "rai",
        "fenugreek seeds",
        "methi seeds",
        "fennel seeds",
        "saunf",
        "asafoetida",
        "hing",
        "cardamom",
        "green cardamom",
        "black cardamom",
        "cloves",
        "cinnamon",
        "bay leaf",
        "tej patta",
        "black pepper",
        "peppercorns",
        "white pepper",
        "nutmeg",
        "mace",
        "star anise",
        "carom seeds",
        "ajwain",
        "nigella seeds",
        "kalonji",
        "dry red chillies",
        "curry leaves",
        "kasuri methi",
        "dried fenugreek leaves",
        "amchur",
        "dry mango powder",
        "chaat masala",
        "sambar powder",
        "rasam powder",
        "pav bhaji masala",
        "chana masala",
        "kitchen king masala",
        "biryani masala",
        "tandoori masala",
        "saffron",
        "kesar",
        "paprika",
        "oregano",
        "thyme",
        "rosemary",
        "dried basil",
        "chilli flakes",
        "red chilli flakes",
        "curry powder",
        "five spice",
        "sumac",
        "za'atar",
        "cajun seasoning",
        "italian seasoning",
        "poppy seeds",
        "khus khus",
        "sesame seeds",
        "til",
        "dried mint",
        "pepper",
    ],
    "grains": [
        "rice",
        "basmati rice",
        "brown rice",
        "sona masoori rice",
        "idli rice",
        "poha",
        "flattened rice",
        "beaten rice",
        "oats",
        "rolled oats",
        "quinoa",
        "semolina",
        "sooji",
        "rava",
        "vermicelli",
        "seviyan",
        "broken wheat",
        "dalia",
        "daliya",
        "bulgur",
        "couscous",
        "pasta",
        "penne",
        "spaghetti",
        "macaroni",
        "noodles",
        "instant noodles",
        "bread",
        "whole wheat bread",
        "pav",
        "buns",
        "tortilla",
        "roti",
        "chapati",
        "puffed rice",
        "murmura",
        "millet",
        "ragi",
        "bajra",
        "jowar",
        "barley",
        "cornflakes",
        "muesli",
        "idli batter",
        "dosa batter",
        "rice noodles",
        "brown bread",
        "pita bread",
        "sabudana",
        "tapioca pearls",
    ],
    "pulses": [
        "toor dal",
        "arhar dal",
        "moong dal",
        "yellow moong dal",
        "green moong",
        "whole moong",
        "masoor dal",
        "red lentils",
        "chana dal",
        "urad dal",
        "black urad dal",
        "urad",
        "rajma",
        "kidney beans",
        "chickpeas",
        "chana",
        "kabuli chana",
        "kala chana",
        "black chickpeas",
        "lobia",
        "black eyed peas",
        "moth beans",
        "matki",
        "horse gram",
        "kulthi",
        "dried peas",
        "soybeans",
        "lentils",
        "split peas",
        "black beans",
        "white beans",
        "cannellini beans",
        "pinto beans",
        "sprouts",
        "moong sprouts",
        "dal",
        "mixed dal",
    ],
    "flours": [
        "atta",
        "wheat flour",
        "whole wheat flour",
        "maida",
        "all purpose flour",
        "plain flour",
        "besan",
        "gram flour",
        "chickpea flour",
        "rice flour",
        "ragi flour",
        "jowar flour",
        "bajra flour",
        "corn flour",
        "cornflour",
        "cornstarch",
        "makki ka atta",
        "cornmeal",
        "bread flour",
        "baking powder",
        "baking soda",
        "yeast",
        "breadcrumbs",
        "cocoa powder",
        "custard powder",
        "multigrain atta",
        "almond flour",
        "oat flour",
    ],
    "dairy": [
        "milk",
        "whole milk",
        "toned milk",
        "curd",
        "yogurt",
        "dahi",
        "greek yogurt",
        "paneer",
        "cottage cheese",
        "cheese",
        "cheddar",
        "mozzarella",
        "parmesan",
        "cream cheese",
        "butter",
        "ghee",
        "cream",
        "fresh cream",
        "heavy cream",
        "whipping cream",
        "sour cream",
        "buttermilk",
        "chaas",
        "khoya",
        "mawa",
        "condensed milk",
        "milk powder",
        "evaporated milk",
        "malai",
        "amul cheese",
        "processed cheese",
        "feta",
        "hung curd",
    ],
    "vegetables": [
        "onion",
        "red onion",
        "spring onion",
        "shallots",
        "garlic",
        "ginger",
        "green chilli",
        "green chillies",
        "green chili",
        "tomato",
        "tomatoes",
        "cherry tomatoes",
        "potato",
        "potatoes",
        "baby potatoes",
        "sweet potato",
        "carrot",
        "spinach",
        "palak",
        "fenugreek leaves",
        "methi",
        "methi leaves",
        "coriander leaves",
        "coriander",
        "cilantro",
        "mint",
        "mint leaves",
        "cabbage",
        "red cabbage",
        "cauliflower",
        "gobi",
        "broccoli",
        "capsicum",
        "bell pepper",
        "red bell pepper",
        "green bell pepper",
        "yellow bell pepper",
        "cucumber",
        "bottle gourd",
        "lauki",
        "ridge gourd",
        "turai",
        "bitter gourd",
        "karela",
        "snake gourd",
        "ash gourd",
        "pumpkin",
        "kaddu",
        "okra",
        "bhindi",
        "lady finger",
        "brinjal",
        "eggplant",
        "aubergine",
        "beetroot",
        "radish",
        "mooli",
        "turnip",
        "drumstick",
        "moringa",
        "french beans",
        "green beans",
        "cluster beans",
        "gawar",
        "flat beans",
        "sem",
        "peas",
        "green peas",
        "mushroom",
        "mushrooms",
        "zucchini",
        "lettuce",
        "iceberg lettuce",
        "kale",
        "celery",
        "leek",
        "sweet corn",
        "baby corn",
        "raw banana",
        "plantain",
        "raw papaya",
        "colocasia",
        "arbi",
        "yam",
        "suran",
        "raw jackfruit",
        "kathal",
        "taro",
        "bok choy",
        "asparagus",
        "tinda",
        "ivy gourd",
        "tindora",
        "parwal",
        "pointed gourd",
        "chow chow",
        "chayote",
        "amaranth leaves",
        "dill",
        "basil",
        "artichoke",
        "spring garlic",
        "corn",
        "cucumbers",
        "carrots",
        "onions",
        "lemongrass",
        "green garlic",
        "sarson",
        "mustard greens",
        "bathua",
        "spinach leaves",
    ],
    "fruits": [
        "apple",
        "banana",
        "mango",
        "orange",
        "lemon",
        "lime",
        "grapes",
        "papaya",
        "pomegranate",
        "watermelon",
        "muskmelon",
        "guava",
        "pineapple",
        "strawberry",
        "strawberries",
        "blueberries",
        "kiwi",
        "pear",
        "peach",
        "plum",
        "cherries",
        "chikoo",
        "sapota",
        "custard apple",
        "lychee",
        "coconut",
        "dry coconut",
        "dates",
        "raisins",
        "kishmish",
        "fig",
        "dried figs",
        "anjeer",
        "apricot",
        "dried apricots",
        "amla",
        "gooseberry",
        "jamun",
        "mosambi",
        "sweet lime",
        "dragon fruit",
        "berries",
        "cranberries",
        "dried cranberries",
        "prunes",
        "avocado",
        "tender coconut",
        "apples",
        "bananas",
        "oranges",
        "lemons",
    ],
    "proteins": [
        "egg",
        "eggs",
        "chicken",
        "chicken breast",
        "chicken thigh",
        "boneless chicken",
        "mutton",
        "lamb",
        "goat meat",
        "fish",
        "salmon",
        "tuna",
        "rohu",
        "pomfret",
        "basa",
        "prawns",
        "shrimp",
        "crab",
        "tofu",
        "tempeh",
        "soya chunks",
        "soy chunks",
        "nutri nuggets",
        "seitan",
        "turkey",
        "beef",
        "pork",
        "bacon",
        "sausages",
        "ham",
        "minced chicken",
        "keema",
        "mince",
        "chicken mince",
        "almonds",
        "cashews",
        "cashew nuts",
        "peanuts",
        "groundnuts",
        "walnuts",
        "pistachios",
        "chia seeds",
        "flax seeds",
        "sunflower seeds",
        "pumpkin seeds",
        "melon seeds",
        "magaz",
        "mixed nuts",
        "makhana",
        "fox nuts",
        "whey protein",
    ],
    "condiments": [
        "soy sauce",
        "vinegar",
        "apple cider vinegar",
        "white vinegar",
        "ketchup",
        "tomato ketchup",
        "tomato puree",
        "tomato paste",
        "mayonnaise",
        "mustard sauce",
        "chilli sauce",
        "green chilli sauce",
        "red chilli sauce",
        "hot sauce",
        "sriracha",
        "green chutney",
        "tamarind",
        "imli",
        "tamarind paste",
        "tamarind chutney",
        "pickle",
        "achar",
        "lemon pickle",
        "mango pickle",
        "jam",
        "peanut butter",
        "honey",
        "sugar",
        "brown sugar",
        "powdered sugar",
        "jaggery",
        "gur",
        "maple syrup",
        "fish sauce",
        "oyster sauce",
        "worcestershire sauce",
        "hoisin sauce",
        "schezwan sauce",
        "pizza sauce",
        "pasta sauce",
        "salsa",
        "hummus",
        "tahini",
        "coconut milk",
        "coconut cream",
        "ginger garlic paste",
        "garlic paste",
        "ginger paste",
        "vanilla extract",
        "vanilla essence",
        "rose water",
        "kewra water",
        "stock cube",
        "bouillon",
        "vegetable stock",
        "chicken stock",
        "miso",
        "gochujang",
        "sambal",
        "harissa",
        "pesto",
        "mustard",
        "chilli paste",
        "desiccated coconut",
        "coconut",
        "lemon juice",
        "nutella",
        "chocolate syrup",
        "mint chutney",
    ],
    "oils": [
        "oil",
        "cooking oil",
        "sunflower oil",
        "vegetable oil",
        "refined oil",
        "mustard oil",
        "coconut oil",
        "olive oil",
        "extra virgin olive oil",
        "groundnut oil",
        "peanut oil",
        "sesame oil",
        "gingelly oil",
        "rice bran oil",
        "canola oil",
        "avocado oil",
        "vanaspati",
        "cooking spray",
        "soybean oil",
    ],
    "snacks": [
        "biscuits",
        "cookies",
        "chips",
        "potato chips",
        "namkeen",
        "bhujia",
        "sev",
        "papad",
        "khakhra",
        "popcorn",
        "chocolate",
        "dark chocolate",
        "granola bar",
        "energy bar",
        "crackers",
        "nachos",
        "mixture",
        "mathri",
        "rusk",
        "cereal",
        "chocolate chips",
        "murukku",
        "chakli",
        "banana chips",
        "trail mix",
        "granola",
        "protein bar",
        "wafers",
    ],
    "beverages": [
        "tea",
        "tea leaves",
        "chai",
        "green tea",
        "coffee",
        "instant coffee",
        "coffee powder",
        "filter coffee",
        "cocoa",
        "drinking chocolate",
        "juice",
        "orange juice",
        "coconut water",
        "soda",
        "sparkling water",
        "energy drink",
        "lemonade",
        "squash",
        "rooh afza",
        "horlicks",
        "bournvita",
        "milk tea",
        "protein powder",
        "oat milk",
        "almond milk",
        "soy milk",
        "kombucha",
        "iced tea",
        "cold drink",
        "cola",
    ],
    "frozen": [
        "frozen peas",
        "frozen corn",
        "frozen mixed vegetables",
        "frozen paratha",
        "frozen spinach",
        "ice cream",
        "frozen berries",
        "frozen momos",
        "momos",
        "frozen fries",
        "french fries",
        "frozen pizza",
        "frozen chicken nuggets",
        "chicken nuggets",
        "nuggets",
        "frozen prawns",
        "ice",
        "edamame",
        "frozen veg cutlet",
        "veg cutlets",
        "frozen fish fingers",
        "fish fingers",
        "frozen dumplings",
    ],
}

KEYWORDS: dict[str, str] = {}
for _category, _names in _RAW.items():
    for _name in _names:
        KEYWORDS.setdefault(normalize_name(_name), _category)

_TOKEN_INDEX: list[tuple[frozenset[str], str, str]] = sorted(
    ((frozenset(k.split()), k, v) for k, v in KEYWORDS.items()),
    key=lambda t: -len(t[0]),
)


def keyword_category(normalized: str) -> str | None:
    """Exact hit, else the longest keyword whose tokens are all present in the name (e.g. 'red onion' -> onion)."""
    if normalized in KEYWORDS:
        return KEYWORDS[normalized]
    name_tokens = set(normalized.split())
    if not name_tokens:
        return None
    for toks, _key, category in _TOKEN_INDEX:
        if toks <= name_tokens:
            return category
    return None


SUGGESTIONS: list[tuple[str, str]] = [
    ("onion", "vegetables"),
    ("tomato", "vegetables"),
    ("potato", "vegetables"),
    ("garlic", "vegetables"),
    ("ginger", "vegetables"),
    ("green chilli", "vegetables"),
    ("coriander leaves", "vegetables"),
    ("spinach", "vegetables"),
    ("carrot", "vegetables"),
    ("capsicum", "vegetables"),
    ("cauliflower", "vegetables"),
    ("cabbage", "vegetables"),
    ("okra", "vegetables"),
    ("cucumber", "vegetables"),
    ("lemon", "fruits"),
    ("banana", "fruits"),
    ("apple", "fruits"),
    ("milk", "dairy"),
    ("curd", "dairy"),
    ("paneer", "dairy"),
    ("butter", "dairy"),
    ("ghee", "dairy"),
    ("cheese", "dairy"),
    ("eggs", "proteins"),
    ("chicken", "proteins"),
    ("peanuts", "proteins"),
    ("almonds", "proteins"),
    ("toor dal", "pulses"),
    ("moong dal", "pulses"),
    ("chana dal", "pulses"),
    ("masoor dal", "pulses"),
    ("rajma", "pulses"),
    ("chickpeas", "pulses"),
    ("urad dal", "pulses"),
    ("basmati rice", "grains"),
    ("rice", "grains"),
    ("poha", "grains"),
    ("oats", "grains"),
    ("semolina", "grains"),
    ("pasta", "grains"),
    ("bread", "grains"),
    ("atta", "flours"),
    ("maida", "flours"),
    ("besan", "flours"),
    ("rice flour", "flours"),
    ("salt", "spices"),
    ("turmeric", "spices"),
    ("red chilli powder", "spices"),
    ("cumin seeds", "spices"),
    ("coriander powder", "spices"),
    ("garam masala", "spices"),
    ("mustard seeds", "spices"),
    ("black pepper", "spices"),
    ("curry leaves", "spices"),
    ("sugar", "condiments"),
    ("jaggery", "condiments"),
    ("tamarind", "condiments"),
    ("soy sauce", "condiments"),
    ("tomato ketchup", "condiments"),
    ("ginger garlic paste", "condiments"),
    ("sunflower oil", "oils"),
    ("mustard oil", "oils"),
    ("olive oil", "oils"),
    ("tea leaves", "beverages"),
    ("coffee", "beverages"),
    ("frozen peas", "frozen"),
]
