"""initial

Revision ID: 0001
Revises: 
Create Date: 2026-09-18 21:17:13.884370

"""
from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '0001'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    op.execute("create extension if not exists pgcrypto")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('profiles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.Text(), nullable=False),
    sa.Column('display_name', sa.Text(), nullable=True),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('sex', sa.Enum('female', 'male', 'other', 'prefer_not_to_say', name='sex_enum'), nullable=True),
    sa.Column('height_cm', sa.SmallInteger(), nullable=True),
    sa.Column('weight_kg', sa.Numeric(precision=5, scale=1), nullable=True),
    sa.Column('activity_level', sa.Enum('sedentary', 'light', 'moderate', 'active', 'very_active', name='activity_enum'), nullable=True),
    sa.Column('diet_type', sa.Enum('omnivore', 'vegetarian', 'eggetarian', 'vegan', 'pescatarian', 'jain', 'other', name='diet_enum'), nullable=True),
    sa.Column('cuisines', postgresql.ARRAY(sa.Text()), server_default=sa.text("'{}'"), nullable=False),
    sa.Column('allergens', postgresql.ARRAY(sa.Text()), server_default=sa.text("'{}'"), nullable=False),
    sa.Column('dislikes', postgresql.ARRAY(sa.Text()), server_default=sa.text("'{}'"), nullable=False),
    sa.Column('likes', postgresql.ARRAY(sa.Text()), server_default=sa.text("'{}'"), nullable=False),
    sa.Column('medical_conditions', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('medical_notes', sa.Text(), nullable=True),
    sa.Column('goals', postgresql.ARRAY(sa.Text()), server_default=sa.text("'{}'"), nullable=False),
    sa.Column('cooking_skill', sa.Enum('beginner', 'intermediate', 'advanced', name='skill_enum'), nullable=True),
    sa.Column('max_prep_minutes', sa.SmallInteger(), nullable=True),
    sa.Column('onboarding_status', sa.Enum('pending', 'in_progress', 'complete', name='onboarding_enum'), server_default='pending', nullable=False),
    sa.Column('onboarding_thread_id', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('households',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('owner_id', sa.UUID(), nullable=False),
    sa.Column('timezone', sa.Text(), server_default='Asia/Kolkata', nullable=False),
    sa.Column('slots', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('weekly_refresh_day', sa.SmallInteger(), server_default='6', nullable=False),
    sa.Column('weekly_refresh_time', sa.Time(), server_default='18:00', nullable=False),
    sa.Column('daily_refresh_time', sa.Time(), server_default='06:00', nullable=False),
    sa.Column('is_implicit', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('household_invites',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('household_id', sa.UUID(), nullable=False),
    sa.Column('code', sa.Text(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('max_uses', sa.SmallInteger(), server_default='10', nullable=False),
    sa.Column('uses', sa.SmallInteger(), server_default='0', nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['profiles.id'], ),
    sa.ForeignKeyConstraint(['household_id'], ['households.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('household_members',
    sa.Column('household_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.Enum('owner', 'member', name='member_role_enum'), nullable=False),
    sa.Column('preferred_view', sa.Enum('single', 'family', name='view_enum'), server_default='family', nullable=False),
    sa.Column('joined_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['household_id'], ['households.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('household_id', 'user_id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('meal_plans',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('household_id', sa.UUID(), nullable=False),
    sa.Column('scope', sa.Enum('family', 'single', name='plan_scope_enum'), nullable=False),
    sa.Column('member_id', sa.UUID(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('active', 'superseded', name='plan_status_enum'), server_default='active', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['household_id'], ['households.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['member_id'], ['profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_meal_plans_lookup', 'meal_plans', ['household_id', 'scope', 'member_id', 'status', 'start_date'], unique=False)
    op.create_table('meals',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('household_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('normalized_name', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('cuisine', sa.Text(), nullable=True),
    sa.Column('meal_types', postgresql.ARRAY(sa.Text()), server_default=sa.text("'{}'"), nullable=False),
    sa.Column('diet_tags', postgresql.ARRAY(sa.Text()), server_default=sa.text("'{}'"), nullable=False),
    sa.Column('allergens', postgresql.ARRAY(sa.Text()), server_default=sa.text("'{}'"), nullable=False),
    sa.Column('prep_minutes', sa.SmallInteger(), nullable=True),
    sa.Column('instructions', sa.Text(), nullable=True),
    sa.Column('source', sa.Enum('user', 'generated', name='meal_source_enum'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('enrichment_status', sa.Enum('pending', 'complete', 'failed', name='enrichment_enum'), server_default='pending', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['profiles.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['household_id'], ['households.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('household_id', 'normalized_name', name='uq_meals_household_name')
    )
    op.create_index('ix_meals_household_source', 'meals', ['household_id', 'source'], unique=False)
    op.create_table('pantry_items',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('household_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('normalized_name', sa.Text(), nullable=False),
    sa.Column('category', sa.Enum('spices', 'grains', 'pulses', 'flours', 'dairy', 'vegetables', 'fruits', 'proteins', 'condiments', 'oils', 'snacks', 'beverages', 'frozen', 'other', name='pantry_category_enum'), nullable=False),
    sa.Column('is_available', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('added_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['added_by'], ['profiles.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['household_id'], ['households.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('household_id', 'normalized_name', name='uq_pantry_household_name')
    )
    op.create_index('ix_pantry_household_category', 'pantry_items', ['household_id', 'category'], unique=False)
    op.create_table('refresh_runs',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('household_id', sa.UUID(), nullable=False),
    sa.Column('kind', sa.Enum('weekly', 'daily', name='refresh_kind_enum'), nullable=False),
    sa.Column('period_key', sa.Text(), nullable=False),
    sa.Column('ran_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('result', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.ForeignKeyConstraint(['household_id'], ['households.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('household_id', 'kind', 'period_key', name='uq_refresh_runs_period')
    )
    op.create_table('meal_ingredients',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('meal_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('normalized_name', sa.Text(), nullable=False),
    sa.Column('category', sa.Enum('spices', 'grains', 'pulses', 'flours', 'dairy', 'vegetables', 'fruits', 'proteins', 'condiments', 'oils', 'snacks', 'beverages', 'frozen', 'other', name='pantry_category_enum'), nullable=False),
    sa.Column('is_staple', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('is_optional', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('position', sa.SmallInteger(), nullable=False),
    sa.ForeignKeyConstraint(['meal_id'], ['meals.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('meal_id', 'normalized_name', name='uq_meal_ingredients_meal_name')
    )
    op.create_table('plan_entries',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('plan_id', sa.UUID(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('slot_key', sa.Text(), nullable=False),
    sa.Column('meal_id', sa.UUID(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('covered_ingredients', postgresql.ARRAY(sa.Text()), server_default=sa.text("'{}'"), nullable=False),
    sa.Column('missing_ingredients', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['meal_id'], ['meals.id'], ),
    sa.ForeignKeyConstraint(['plan_id'], ['meal_plans.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('plan_id', 'date', 'slot_key', name='uq_plan_entries_plan_date_slot')
    )
    op.create_table('plan_jobs',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('plan_id', sa.UUID(), nullable=False),
    sa.Column('mode', sa.Enum('week', 'today', 'slot', name='job_mode_enum'), nullable=False),
    sa.Column('origin', sa.Enum('user', 'scheduler', 'onboarding', name='job_origin_enum'), nullable=False),
    sa.Column('target_date', sa.Date(), nullable=True),
    sa.Column('target_slot_key', sa.Text(), nullable=True),
    sa.Column('target_entry_id', sa.UUID(), nullable=True),
    sa.Column('swap_reason', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('queued', 'running', 'ready', 'failed', name='job_status_enum'), server_default='queued', nullable=False),
    sa.Column('inputs_hash', sa.Text(), nullable=True),
    sa.Column('model_name', sa.Text(), nullable=True),
    sa.Column('attempts', sa.SmallInteger(), server_default='0', nullable=False),
    sa.Column('used_fallback', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['plan_id'], ['meal_plans.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_plan_jobs_plan_status', 'plan_jobs', ['plan_id', 'status'], unique=False)
    op.create_table('meal_feedback',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('household_id', sa.UUID(), nullable=False),
    sa.Column('member_id', sa.UUID(), nullable=False),
    sa.Column('meal_id', sa.UUID(), nullable=False),
    sa.Column('plan_entry_id', sa.UUID(), nullable=True),
    sa.Column('kind', sa.Enum('up', 'down', 'cooked', 'skipped', name='feedback_enum'), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['household_id'], ['households.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['meal_id'], ['meals.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['member_id'], ['profiles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['plan_entry_id'], ['plan_entries.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_meal_feedback_household_meal', 'meal_feedback', ['household_id', 'meal_id'], unique=False)
    op.create_table('plan_entry_variations',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('plan_entry_id', sa.UUID(), nullable=False),
    sa.Column('member_id', sa.UUID(), nullable=False),
    sa.Column('note', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['member_id'], ['profiles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['plan_entry_id'], ['plan_entries.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('plan_entry_id', 'member_id', name='uq_plan_entry_variations_entry_member')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('plan_entry_variations')
    op.drop_index('ix_meal_feedback_household_meal', table_name='meal_feedback')
    op.drop_table('meal_feedback')
    op.drop_index('ix_plan_jobs_plan_status', table_name='plan_jobs')
    op.drop_table('plan_jobs')
    op.drop_table('plan_entries')
    op.drop_table('meal_ingredients')
    op.drop_table('refresh_runs')
    op.drop_index('ix_pantry_household_category', table_name='pantry_items')
    op.drop_table('pantry_items')
    op.drop_index('ix_meals_household_source', table_name='meals')
    op.drop_table('meals')
    op.drop_index('ix_meal_plans_lookup', table_name='meal_plans')
    op.drop_table('meal_plans')
    op.drop_table('household_members')
    op.drop_table('household_invites')
    op.drop_table('households')
    op.drop_table('profiles')
    # ### end Alembic commands ###
    op.execute("drop type if exists activity_enum")
    op.execute("drop type if exists diet_enum")
    op.execute("drop type if exists enrichment_enum")
    op.execute("drop type if exists feedback_enum")
    op.execute("drop type if exists job_mode_enum")
    op.execute("drop type if exists job_origin_enum")
    op.execute("drop type if exists job_status_enum")
    op.execute("drop type if exists meal_source_enum")
    op.execute("drop type if exists member_role_enum")
    op.execute("drop type if exists onboarding_enum")
    op.execute("drop type if exists pantry_category_enum")
    op.execute("drop type if exists plan_scope_enum")
    op.execute("drop type if exists plan_status_enum")
    op.execute("drop type if exists refresh_kind_enum")
    op.execute("drop type if exists sex_enum")
    op.execute("drop type if exists skill_enum")
    op.execute("drop type if exists view_enum")
