/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_v1_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Me */
        get: operations["get_me_api_v1_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Patch Me */
        patch: operations["patch_me_api_v1_me_patch"];
        trace?: never;
    };
    "/api/v1/onboarding/start": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Start */
        post: operations["start_api_v1_onboarding_start_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/onboarding/turn": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Turn */
        post: operations["turn_api_v1_onboarding_turn_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/onboarding/complete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Complete */
        post: operations["complete_api_v1_onboarding_complete_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/households/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** My Household */
        get: operations["my_household_api_v1_households_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/households/join": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Join */
        post: operations["join_api_v1_households_join_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/households/{household_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Patch Household */
        patch: operations["patch_household_api_v1_households__household_id__patch"];
        trace?: never;
    };
    "/api/v1/households/{household_id}/invites": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Invites */
        get: operations["list_invites_api_v1_households__household_id__invites_get"];
        put?: never;
        /** Create Invite */
        post: operations["create_invite_api_v1_households__household_id__invites_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/households/{household_id}/invites/{code}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Revoke Invite */
        delete: operations["revoke_invite_api_v1_households__household_id__invites__code__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/households/{household_id}/members/{user_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Remove Member */
        delete: operations["remove_member_api_v1_households__household_id__members__user_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/households/{household_id}/members/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Set Preferred View */
        patch: operations["set_preferred_view_api_v1_households__household_id__members_me_patch"];
        trace?: never;
    };
    "/api/v1/pantry": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Pantry */
        get: operations["get_pantry_api_v1_pantry_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/pantry/suggestions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Suggestions */
        get: operations["get_suggestions_api_v1_pantry_suggestions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/pantry/items": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Add Items */
        post: operations["add_items_api_v1_pantry_items_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/pantry/items/{item_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Item */
        delete: operations["delete_item_api_v1_pantry_items__item_id__delete"];
        options?: never;
        head?: never;
        /** Patch Item */
        patch: operations["patch_item_api_v1_pantry_items__item_id__patch"];
        trace?: never;
    };
    "/api/v1/meals": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Meals */
        get: operations["list_meals_api_v1_meals_get"];
        put?: never;
        /** Create Meal */
        post: operations["create_meal_api_v1_meals_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/meals/{meal_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Meal */
        get: operations["get_meal_api_v1_meals__meal_id__get"];
        put?: never;
        post?: never;
        /** Delete Meal */
        delete: operations["delete_meal_api_v1_meals__meal_id__delete"];
        options?: never;
        head?: never;
        /** Patch Meal */
        patch: operations["patch_meal_api_v1_meals__meal_id__patch"];
        trace?: never;
    };
    "/api/v1/meals/{meal_id}/enrich": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Enrich */
        post: operations["enrich_api_v1_meals__meal_id__enrich_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/meals/{meal_id}/feedback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Feedback */
        post: operations["feedback_api_v1_meals__meal_id__feedback_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/plans/current": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Current Plan */
        get: operations["current_plan_api_v1_plans_current_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/plans/generate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Generate */
        post: operations["generate_api_v1_plans_generate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/plans/{plan_id}/entries/{entry_id}/swap": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Swap */
        post: operations["swap_api_v1_plans__plan_id__entries__entry_id__swap_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/plans/{plan_id}/shopping-list": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Shopping List */
        get: operations["shopping_list_api_v1_plans__plan_id__shopping_list_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/plans/jobs/{job_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Job */
        get: operations["job_api_v1_plans_jobs__job_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/internal/scheduler/tick": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Tick */
        post: operations["tick_api_v1_internal_scheduler_tick_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** ActiveJobOut */
        ActiveJobOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Mode
             * @enum {string}
             */
            mode: "week" | "today" | "slot";
            /**
             * Status
             * @enum {string}
             */
            status: "queued" | "running" | "ready" | "failed";
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** ChipsWidget */
        ChipsWidget: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "chips";
            /**
             * Suggestions
             * @default []
             */
            suggestions: string[];
            /**
             * Placeholder
             * @default
             */
            placeholder: string;
            /**
             * Max
             * @default 20
             */
            max: number;
        };
        /** CompleteRequest */
        CompleteRequest: {
            /** Thread Id */
            thread_id: string;
            overrides?: components["schemas"]["ProfilePatch"] | null;
        };
        /** CompleteResponse */
        CompleteResponse: {
            profile: components["schemas"]["ProfileOut"];
            household: components["schemas"]["HouseholdOut"];
            /** First Plan Job Id */
            first_plan_job_id: string | null;
        };
        /** CoverageOut */
        CoverageOut: {
            /** On Hand */
            on_hand: number;
            /** Needed */
            needed: number;
        };
        /** CurrentPlanOut */
        CurrentPlanOut: {
            plan: components["schemas"]["PlanOut"] | null;
            active_job: components["schemas"]["ActiveJobOut"] | null;
        };
        /** DateWidget */
        DateWidget: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "date";
            /**
             * Min
             * Format: date
             */
            min: string;
            /**
             * Max
             * Format: date
             */
            max: string;
        };
        /** FeedbackCreate */
        FeedbackCreate: {
            /**
             * Kind
             * @enum {string}
             */
            kind: "up" | "down" | "cooked" | "skipped";
            /** Plan Entry Id */
            plan_entry_id?: string | null;
            /** Comment */
            comment?: string | null;
        };
        /** FeedbackOut */
        FeedbackOut: {
            feedback: components["schemas"]["FeedbackSummary"];
        };
        /** FeedbackSummary */
        FeedbackSummary: {
            /**
             * Up
             * @default 0
             */
            up: number;
            /**
             * Down
             * @default 0
             */
            down: number;
            /**
             * Cooked
             * @default 0
             */
            cooked: number;
            /** Last Cooked At */
            last_cooked_at?: string | null;
        };
        /** GenerateRequest */
        GenerateRequest: {
            /**
             * Scope
             * @enum {string}
             */
            scope: "family" | "single";
            /**
             * Mode
             * @enum {string}
             */
            mode: "week" | "today";
            /** Date */
            date?: string | null;
        };
        /** GenerateResponse */
        GenerateResponse: {
            /**
             * Job Id
             * Format: uuid
             */
            job_id: string;
            /**
             * Plan Id
             * Format: uuid
             */
            plan_id: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HouseholdOut */
        HouseholdOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            /**
             * Owner Id
             * Format: uuid
             */
            owner_id: string;
            /** Timezone */
            timezone: string;
            /** Slots */
            slots: components["schemas"]["SlotDef"][];
            /** Weekly Refresh Day */
            weekly_refresh_day: number;
            /**
             * Weekly Refresh Time
             * Format: time
             */
            weekly_refresh_time: string;
            /**
             * Daily Refresh Time
             * Format: time
             */
            daily_refresh_time: string;
            /** Is Implicit */
            is_implicit: boolean;
            /** Members */
            members: components["schemas"]["MemberSummary"][];
        };
        /** HouseholdPatch */
        HouseholdPatch: {
            /** Name */
            name?: string | null;
            /** Timezone */
            timezone?: string | null;
            /** Slots */
            slots?: components["schemas"]["SlotDef"][] | null;
            /** Weekly Refresh Day */
            weekly_refresh_day?: number | null;
            /** Weekly Refresh Time */
            weekly_refresh_time?: string | null;
            /** Daily Refresh Time */
            daily_refresh_time?: string | null;
        };
        /** IngredientDraft */
        IngredientDraft: {
            /** Name */
            name: string;
            /**
             * Category
             * @default other
             * @enum {string}
             */
            category: "spices" | "grains" | "pulses" | "flours" | "dairy" | "vegetables" | "fruits" | "proteins" | "condiments" | "oils" | "snacks" | "beverages" | "frozen" | "other";
            /**
             * Is Staple
             * @default false
             */
            is_staple: boolean;
            /**
             * Is Optional
             * @default false
             */
            is_optional: boolean;
        };
        /** IngredientOut */
        IngredientOut: {
            /** Name */
            name: string;
            /**
             * Category
             * @enum {string}
             */
            category: "spices" | "grains" | "pulses" | "flours" | "dairy" | "vegetables" | "fruits" | "proteins" | "condiments" | "oils" | "snacks" | "beverages" | "frozen" | "other";
            /** Is Staple */
            is_staple: boolean;
            /** Is Optional */
            is_optional: boolean;
        };
        /** InviteCreate */
        InviteCreate: {
            /**
             * Expires In Days
             * @default 7
             */
            expires_in_days: number;
            /**
             * Max Uses
             * @default 10
             */
            max_uses: number;
        };
        /** InviteOut */
        InviteOut: {
            /** Code */
            code: string;
            /**
             * Expires At
             * Format: date-time
             */
            expires_at: string;
            /** Max Uses */
            max_uses: number;
            /** Uses */
            uses: number;
        };
        /** JobOut */
        JobOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Plan Id
             * Format: uuid
             */
            plan_id: string;
            /**
             * Mode
             * @enum {string}
             */
            mode: "week" | "today" | "slot";
            /**
             * Status
             * @enum {string}
             */
            status: "queued" | "running" | "ready" | "failed";
            /** Error */
            error: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Started At */
            started_at: string | null;
            /** Finished At */
            finished_at: string | null;
        };
        /** JoinRequest */
        JoinRequest: {
            /** Code */
            code: string;
        };
        /** MeOut */
        MeOut: {
            profile: components["schemas"]["ProfileOut"];
            household: components["schemas"]["HouseholdOut"] | null;
            /**
             * Onboarding Status
             * @enum {string}
             */
            onboarding_status: "pending" | "in_progress" | "complete";
        };
        /** MealCreate */
        MealCreate: {
            /** Name */
            name: string;
            /** Description */
            description?: string | null;
            /** Ingredients */
            ingredients?: string[] | null;
            /** Instructions */
            instructions?: string | null;
        };
        /** MealOut */
        MealOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            /** Description */
            description: string | null;
            /** Cuisine */
            cuisine: string | null;
            /** Meal Types */
            meal_types: string[];
            /** Diet Tags */
            diet_tags: string[];
            /** Allergens */
            allergens: string[];
            /** Prep Minutes */
            prep_minutes: number | null;
            /** Instructions */
            instructions: string | null;
            /** Source */
            source: string;
            /** Enrichment Status */
            enrichment_status: string;
            /** Ingredients */
            ingredients: components["schemas"]["IngredientOut"][];
            feedback: components["schemas"]["FeedbackSummary"];
        };
        /** MealPatch */
        MealPatch: {
            /** Name */
            name?: string | null;
            /** Description */
            description?: string | null;
            /** Cuisine */
            cuisine?: string | null;
            /** Meal Types */
            meal_types?: string[] | null;
            /** Diet Tags */
            diet_tags?: string[] | null;
            /** Allergens */
            allergens?: string[] | null;
            /** Prep Minutes */
            prep_minutes?: number | null;
            /** Instructions */
            instructions?: string | null;
            /** Ingredients */
            ingredients?: components["schemas"]["IngredientDraft"][] | null;
        };
        /** MealsOut */
        MealsOut: {
            /** Meals */
            meals: components["schemas"]["MealOut"][];
        };
        /** MedicalCondition */
        MedicalCondition: {
            /** Name */
            name: string;
            /** Notes */
            notes?: string | null;
        };
        /** MemberSummary */
        MemberSummary: {
            /**
             * User Id
             * Format: uuid
             */
            user_id: string;
            /** Display Name */
            display_name: string | null;
            /**
             * Role
             * @enum {string}
             */
            role: "owner" | "member";
            /**
             * Preferred View
             * @enum {string}
             */
            preferred_view: "single" | "family";
        };
        /** MissingIngredientOut */
        MissingIngredientOut: {
            /** Name */
            name: string;
            /**
             * Category
             * @enum {string}
             */
            category: "spices" | "grains" | "pulses" | "flours" | "dairy" | "vegetables" | "fruits" | "proteins" | "condiments" | "oils" | "snacks" | "beverages" | "frozen" | "other";
            /**
             * Is Optional
             * @default false
             */
            is_optional: boolean;
        };
        /** MultiSelectWidget */
        MultiSelectWidget: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "multi_select";
            /** Options */
            options: components["schemas"]["Option"][];
            /**
             * Allow Custom
             * @default false
             */
            allow_custom: boolean;
            /**
             * Min
             * @default 0
             */
            min: number;
            /**
             * Max
             * @default 20
             */
            max: number;
        };
        /** NumberWidget */
        NumberWidget: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "number";
            /** Unit */
            unit: string;
            /** Min */
            min: number;
            /** Max */
            max: number;
            /**
             * Step
             * @default 1
             */
            step: number;
        };
        /** Option */
        Option: {
            /** Value */
            value: string;
            /** Label */
            label: string;
            /** Description */
            description?: string | null;
        };
        /** PantryAddRequest */
        PantryAddRequest: {
            /** Items */
            items: components["schemas"]["PantryItemIn"][];
        };
        /** PantryAddResponse */
        PantryAddResponse: {
            /** Created */
            created: components["schemas"]["PantryItemOut"][];
            /** Existing */
            existing: components["schemas"]["PantryItemOut"][];
        };
        /** PantryCategoryGroup */
        PantryCategoryGroup: {
            /**
             * Category
             * @enum {string}
             */
            category: "spices" | "grains" | "pulses" | "flours" | "dairy" | "vegetables" | "fruits" | "proteins" | "condiments" | "oils" | "snacks" | "beverages" | "frozen" | "other";
            /** Label */
            label: string;
            /** Items */
            items: components["schemas"]["PantryItemOut"][];
        };
        /** PantryItemIn */
        PantryItemIn: {
            /** Name */
            name: string;
            /** Category */
            category?: ("spices" | "grains" | "pulses" | "flours" | "dairy" | "vegetables" | "fruits" | "proteins" | "condiments" | "oils" | "snacks" | "beverages" | "frozen" | "other") | null;
        };
        /** PantryItemOut */
        PantryItemOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            /**
             * Category
             * @enum {string}
             */
            category: "spices" | "grains" | "pulses" | "flours" | "dairy" | "vegetables" | "fruits" | "proteins" | "condiments" | "oils" | "snacks" | "beverages" | "frozen" | "other";
            /** Is Available */
            is_available: boolean;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** PantryItemPatch */
        PantryItemPatch: {
            /** Name */
            name?: string | null;
            /** Category */
            category?: ("spices" | "grains" | "pulses" | "flours" | "dairy" | "vegetables" | "fruits" | "proteins" | "condiments" | "oils" | "snacks" | "beverages" | "frozen" | "other") | null;
            /** Is Available */
            is_available?: boolean | null;
        };
        /** PantryOut */
        PantryOut: {
            /** Categories */
            categories: components["schemas"]["PantryCategoryGroup"][];
            /** Total */
            total: number;
        };
        /** PlanDayOut */
        PlanDayOut: {
            /**
             * Date
             * Format: date
             */
            date: string;
            /** Entries */
            entries: components["schemas"]["PlanEntryOut"][];
        };
        /** PlanEntryOut */
        PlanEntryOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Date
             * Format: date
             */
            date: string;
            /** Slot Key */
            slot_key: string;
            /** Slot Label */
            slot_label: string;
            meal: components["schemas"]["MealOut"];
            /** Reason */
            reason: string;
            /** Covered Ingredients */
            covered_ingredients: string[];
            /** Missing Ingredients */
            missing_ingredients: components["schemas"]["MissingIngredientOut"][];
            /** Variations */
            variations: components["schemas"]["VariationOut"][];
            /** My Feedback */
            my_feedback: ("up" | "down") | null;
            /** Cooked Count */
            cooked_count: number;
        };
        /** PlanOut */
        PlanOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Scope
             * @enum {string}
             */
            scope: "family" | "single";
            /** Member Id */
            member_id: string | null;
            /**
             * Start Date
             * Format: date
             */
            start_date: string;
            /**
             * End Date
             * Format: date
             */
            end_date: string;
            /** Days */
            days: components["schemas"]["PlanDayOut"][];
            coverage: components["schemas"]["CoverageOut"];
            /** Unused Pantry */
            unused_pantry: components["schemas"]["UnusedItemOut"][];
        };
        /** PreferredViewPatch */
        PreferredViewPatch: {
            /**
             * Preferred View
             * @enum {string}
             */
            preferred_view: "single" | "family";
        };
        /** ProfileDraft */
        ProfileDraft: {
            /** Display Name */
            display_name?: string | null;
            /** Date Of Birth */
            date_of_birth?: string | null;
            /** Sex */
            sex?: string | null;
            /** Height Cm */
            height_cm?: number | null;
            /** Weight Kg */
            weight_kg?: number | null;
            /** Activity Level */
            activity_level?: string | null;
            /** Diet Type */
            diet_type?: string | null;
            /** Cuisines */
            cuisines?: string[] | null;
            /** Allergens */
            allergens?: string[] | null;
            /** Dislikes */
            dislikes?: string[] | null;
            /** Likes */
            likes?: string[] | null;
            /** Medical Conditions */
            medical_conditions?: components["schemas"]["MedicalCondition"][] | null;
            /** Medical Notes */
            medical_notes?: string | null;
            /** Goals */
            goals?: string[] | null;
            /** Cooking Skill */
            cooking_skill?: string | null;
            /** Max Prep Minutes */
            max_prep_minutes?: number | null;
        };
        /** ProfileOut */
        ProfileOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Email */
            email: string;
            /** Display Name */
            display_name: string | null;
            /** Date Of Birth */
            date_of_birth: string | null;
            /** Sex */
            sex: string | null;
            /** Height Cm */
            height_cm: number | null;
            /** Weight Kg */
            weight_kg: number | null;
            /** Activity Level */
            activity_level: string | null;
            /** Diet Type */
            diet_type: string | null;
            /** Cuisines */
            cuisines: string[];
            /** Allergens */
            allergens: string[];
            /** Dislikes */
            dislikes: string[];
            /** Likes */
            likes: string[];
            /** Medical Conditions */
            medical_conditions: components["schemas"]["MedicalCondition"][];
            /** Medical Notes */
            medical_notes: string | null;
            /** Goals */
            goals: string[];
            /** Cooking Skill */
            cooking_skill: string | null;
            /** Max Prep Minutes */
            max_prep_minutes: number | null;
            /**
             * Onboarding Status
             * @enum {string}
             */
            onboarding_status: "pending" | "in_progress" | "complete";
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** ProfilePatch */
        ProfilePatch: {
            /** Display Name */
            display_name?: string | null;
            /** Date Of Birth */
            date_of_birth?: string | null;
            /** Sex */
            sex?: ("female" | "male" | "other" | "prefer_not_to_say") | null;
            /** Height Cm */
            height_cm?: number | null;
            /** Weight Kg */
            weight_kg?: number | null;
            /** Activity Level */
            activity_level?: ("sedentary" | "light" | "moderate" | "active" | "very_active") | null;
            /** Diet Type */
            diet_type?: ("omnivore" | "vegetarian" | "eggetarian" | "vegan" | "pescatarian" | "jain" | "other") | null;
            /** Cuisines */
            cuisines?: string[] | null;
            /** Allergens */
            allergens?: string[] | null;
            /** Dislikes */
            dislikes?: string[] | null;
            /** Likes */
            likes?: string[] | null;
            /** Medical Conditions */
            medical_conditions?: components["schemas"]["MedicalCondition"][] | null;
            /** Medical Notes */
            medical_notes?: string | null;
            /** Goals */
            goals?: string[] | null;
            /** Cooking Skill */
            cooking_skill?: ("beginner" | "intermediate" | "advanced") | null;
            /** Max Prep Minutes */
            max_prep_minutes?: number | null;
        };
        /** Progress */
        Progress: {
            /** Answered */
            answered: number;
            /** Total */
            total: number;
        };
        /** ReviewWidget */
        ReviewWidget: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "review";
            draft: components["schemas"]["ProfileDraft"];
        };
        /** ShoppingGroupOut */
        ShoppingGroupOut: {
            /**
             * Category
             * @enum {string}
             */
            category: "spices" | "grains" | "pulses" | "flours" | "dairy" | "vegetables" | "fruits" | "proteins" | "condiments" | "oils" | "snacks" | "beverages" | "frozen" | "other";
            /** Label */
            label: string;
            /** Items */
            items: components["schemas"]["ShoppingItemOut"][];
        };
        /** ShoppingItemOut */
        ShoppingItemOut: {
            /** Name */
            name: string;
            /** Meals */
            meals: string[];
        };
        /** ShoppingListOut */
        ShoppingListOut: {
            /**
             * From Date
             * Format: date
             */
            from_date: string;
            /**
             * To Date
             * Format: date
             */
            to_date: string;
            /** Groups */
            groups: components["schemas"]["ShoppingGroupOut"][];
            /** Total */
            total: number;
        };
        /** SingleSelectWidget */
        SingleSelectWidget: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "single_select";
            /** Options */
            options: components["schemas"]["Option"][];
        };
        /** SlotDef */
        SlotDef: {
            /** Key */
            key: string;
            /** Label */
            label: string;
            /** Order */
            order: number;
        };
        /** SuggestionItem */
        SuggestionItem: {
            /** Name */
            name: string;
            /**
             * Category
             * @enum {string}
             */
            category: "spices" | "grains" | "pulses" | "flours" | "dairy" | "vegetables" | "fruits" | "proteins" | "condiments" | "oils" | "snacks" | "beverages" | "frozen" | "other";
        };
        /** SuggestionsOut */
        SuggestionsOut: {
            /** Items */
            items: components["schemas"]["SuggestionItem"][];
        };
        /** SwapRequest */
        SwapRequest: {
            /** Reason */
            reason?: string | null;
        };
        /** SwapResponse */
        SwapResponse: {
            /**
             * Job Id
             * Format: uuid
             */
            job_id: string;
        };
        /** TextAnswer */
        TextAnswer: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "text";
            /** Text */
            text: string;
        };
        /** TextWidget */
        TextWidget: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "text";
            /**
             * Placeholder
             * @default
             */
            placeholder: string;
            /**
             * Multiline
             * @default false
             */
            multiline: boolean;
            /**
             * Max Length
             * @default 200
             */
            max_length: number;
        };
        /** TickReport */
        TickReport: {
            /**
             * Ran At
             * Format: date-time
             */
            ran_at: string;
            /**
             * Households Checked
             * @default 0
             */
            households_checked: number;
            /** Weekly Enqueued */
            weekly_enqueued?: string[];
            /** Daily Enqueued */
            daily_enqueued?: string[];
            /**
             * Skipped
             * @default 0
             */
            skipped: number;
            /**
             * Cleaned Plans
             * @default 0
             */
            cleaned_plans: number;
        };
        /** TurnRequest */
        TurnRequest: {
            /** Thread Id */
            thread_id: string;
            /** Answer */
            answer: components["schemas"]["WidgetAnswer"] | components["schemas"]["TextAnswer"];
        };
        /** TurnResponse */
        TurnResponse: {
            /** Thread Id */
            thread_id: string;
            /** Message */
            message: string;
            /** Widget */
            widget: (components["schemas"]["TextWidget"] | components["schemas"]["NumberWidget"] | components["schemas"]["DateWidget"] | components["schemas"]["SingleSelectWidget"] | components["schemas"]["MultiSelectWidget"] | components["schemas"]["ChipsWidget"] | components["schemas"]["ReviewWidget"]) | null;
            /** Field */
            field: string | null;
            draft: components["schemas"]["ProfileDraft"];
            progress: components["schemas"]["Progress"];
            /** Is Complete */
            is_complete: boolean;
        };
        /** UnusedItemOut */
        UnusedItemOut: {
            /** Name */
            name: string;
            /**
             * Category
             * @enum {string}
             */
            category: "spices" | "grains" | "pulses" | "flours" | "dairy" | "vegetables" | "fruits" | "proteins" | "condiments" | "oils" | "snacks" | "beverages" | "frozen" | "other";
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** VariationOut */
        VariationOut: {
            /**
             * Member Id
             * Format: uuid
             */
            member_id: string;
            /** Display Name */
            display_name: string | null;
            /** Note */
            note: string;
        };
        /** WidgetAnswer */
        WidgetAnswer: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "widget";
            /** Value */
            value: unknown;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_api_v1_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    get_me_api_v1_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeOut"];
                };
            };
        };
    };
    patch_me_api_v1_me_patch: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProfilePatch"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProfileOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    start_api_v1_onboarding_start_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TurnResponse"];
                };
            };
        };
    };
    turn_api_v1_onboarding_turn_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TurnRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TurnResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    complete_api_v1_onboarding_complete_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CompleteRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CompleteResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    my_household_api_v1_households_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HouseholdOut"];
                };
            };
        };
    };
    join_api_v1_households_join_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["JoinRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HouseholdOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    patch_household_api_v1_households__household_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                household_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["HouseholdPatch"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HouseholdOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_invites_api_v1_households__household_id__invites_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                household_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InviteOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_invite_api_v1_households__household_id__invites_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                household_id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["InviteCreate"] | null;
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InviteOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    revoke_invite_api_v1_households__household_id__invites__code__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                household_id: string;
                code: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    remove_member_api_v1_households__household_id__members__user_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                household_id: string;
                user_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    set_preferred_view_api_v1_households__household_id__members_me_patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                household_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PreferredViewPatch"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MemberSummary"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_pantry_api_v1_pantry_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PantryOut"];
                };
            };
        };
    };
    get_suggestions_api_v1_pantry_suggestions_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SuggestionsOut"];
                };
            };
        };
    };
    add_items_api_v1_pantry_items_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PantryAddRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PantryAddResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_item_api_v1_pantry_items__item_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                item_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    patch_item_api_v1_pantry_items__item_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                item_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PantryItemPatch"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PantryItemOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_meals_api_v1_meals_get: {
        parameters: {
            query?: {
                query?: string | null;
                meal_type?: string | null;
                source?: "user" | "generated" | "all";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MealsOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_meal_api_v1_meals_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MealCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MealOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_meal_api_v1_meals__meal_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                meal_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MealOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_meal_api_v1_meals__meal_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                meal_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    patch_meal_api_v1_meals__meal_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                meal_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MealPatch"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MealOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    enrich_api_v1_meals__meal_id__enrich_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                meal_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MealOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    feedback_api_v1_meals__meal_id__feedback_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                meal_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FeedbackCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FeedbackOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    current_plan_api_v1_plans_current_get: {
        parameters: {
            query?: {
                scope?: ("family" | "single") | null;
                date?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CurrentPlanOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    generate_api_v1_plans_generate_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GenerateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GenerateResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    swap_api_v1_plans__plan_id__entries__entry_id__swap_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                plan_id: string;
                entry_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SwapRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SwapResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    shopping_list_api_v1_plans__plan_id__shopping_list_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                plan_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ShoppingListOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    job_api_v1_plans_jobs__job_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    tick_api_v1_internal_scheduler_tick_post: {
        parameters: {
            query?: never;
            header?: {
                "x-scheduler-secret"?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TickReport"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
